export enum TokenSymbol {
    MONMonad = 'MON',
    WMONMonad = 'WMON',
    DAKMonad = 'DAK',
    CHOGMonad = 'CHODG',
    YAKIMonad = 'YAKI',
    USDCMonad = 'USDC',
    USDTMonad = 'USDT',
    USDTOMonad = 'USDT0',
    WBTCMonad = 'WBTC',
    WETHMonad = 'WETH',
    WSOLMonad = 'WSOL',
    ANAGOMonad = 'Anago',
    NAPMonad = 'NAP',
    SHMONMonad = 'shMON',
}
