export enum TokenSymbol {
    IZI= 'iZi',
    ETH= 'ETH',
    WETH= 'WETH',
    USDC= 'USDC',
    USDT= 'USDT',
    ACY= 'ACY',
    DAI= 'DAI',
    BIT= 'BIT', // BitDao
    MIM= 'MIM',
    stETH= 'stETH',
    SPELL= 'SPELL',
    LIDO= 'LIDO',
    YIN= 'YIN',
    DEVT= 'DEVT',
    DDAO= 'DDAO',
    BUSD= 'BUSD',
    WBNB= 'WBNB',
    BNB= 'BNB',
    DOGE= 'DOGE',
    SHIB= 'SHIB',
    IUSD= 'iUSD',
    ARC = 'ARC',
    AURORA = 'AURORA',
}
