export enum TokenSymbol {
    USDCLinea = 'USDC',
    USDCNative = 'USDC',
    USDTLinea = 'USDT',
    USDTNative = 'USDT',
    DAILinea = 'DAI',
    UNILinea = 'UNI',
    HOPLinea = 'HOP',
    BNBLinea = 'BNB',
    BUSDLinea = 'BUSD',
    AVAXLinea = 'AVAX',
    TUSDLinea = 'TUSD',
    EUROLinea = 'EUROe',
    MATICLinea = 'MATIC',
}
