export enum TokenSymbol {
    CEBUSDLinea = 'BUSD',
    USDCLinea = 'USDC',
    WBTCLinea = 'WBTC',
    USDTLinea = 'USDT',
    LABLinea = 'LAB',
    ZKUSDLinea = 'ZKUSD',
    LYULinea = 'LYU',
    LINELinea = 'LINE',
    EZETHLinea = 'ezETH',
    ZEROLinea = 'ZERO',
    WEETHLinea = 'weETH',
    SOLVBTCLinea = 'SolvBTC.m',
    MBTCLinea = 'M-BTC',
    FOXYLinea = 'FOXY',
}
