export enum TokenSymbol {
    WETHMANTLE = 'WETH',
    MNTMANTLE = 'MNT',
    WMNTMANTLE = 'WMNT',
    USDTMANTLE = 'USDT',
    LUSDMANTLE = 'LUSD',
    PENDLEMANTLE = 'PENDLE',
    WBTCMANTLE = 'WBTC',
    WSTETHMANTLE = 'wstETH',
    USDCMANTLE = 'USDC',
}
