export enum TokenSymbol {
   LUNA = 'LUNA',
   XRP = 'XRP',
   BSW = 'BSW',
   UNI = 'UNI',
   LTC = 'LTC',
   SOL = 'SOL',
   SHIB = 'SHIB',
   DOT = 'DOT',
   TRX = 'TRX',
   LINK = 'LINK',
   FIL = 'FIL',
   WOM = 'WOM',
   WMX = 'WMX',
}
