export enum TokenSymbol {
    DOGERA = 'DOGERA',
    BOLT = 'BOLT',
    CHEEMS = 'Cheems',
    SLUSDT = 'USDT',
    SLSTETH = 'stETH',
    SLBTC = 'BTC',
    ZKSP = 'ZKSP',
    DEXTF = 'DEXTF',
    RF = 'RF',
    ZAT = 'ZAT',
    GEJU = 'GEJU',
    VS = 'VS',
    OT = 'OT',
    SPACE = 'SPACE',
    ERA = 'ERA',
    BLADE = 'BLADE',
    ZNS = 'ZNS',
    ESZKDX = 'esZKDX',
}
