export enum TokenSymbol {
    CCC = 'CCC',
    TINC = 'TINC',
    ARBIBSC = 'ARBI',
    TPT = 'TPT',
    DUET = "DUET",
    DUSD = "dUSD",
    DWTI = "dWTI",
    DXAU = "dXAU",
    BURGER = "BURGER",
    MW = "MW",
    SLD = "SLD",
    KSW = "KSW",
    LAND = "LAND",
    REVO = "REVO",
    FROYO = "FROYO",
    NAS = "NAS",
    IOM = "IOM",
    ZVC = "ZVC",
    MNW = "MNW",
    MELT = "MELT",
    GE = "GE",
    RIV = "RIV",
}
