export enum TokenSymbol {
    MTR = 'MTR',
    WMTR = 'WMTR',
    MTRG = 'MTRG',
    USDTETH = 'USDT.eth',
    BUSDBSC = 'BUSD.bsc',
    AMPLMETER = 'AMPL',
    BNBBSC = 'BNB',
    CIVMETER  = 'CIV',
    ETHETH = 'ETH',
    FTBMETER = 'FTB',
    IUSDMETER = 'iUSD',
    IZIMETER = 'iZi',
    MENMETER = 'MEN',
    MOVRMETER = 'MOVR',
    SKILLMETER = 'SKILL',
    TDROPMETER = 'TDROP',
    TFUELMETER = 'TFUEL',
    USDCETH = 'USDC.eth',
    VOLTMETER = 'VOLT',
    WBTCETH = 'WBTC.eth',
}
