export enum TokenSymbol {
    AAVEScroll = 'AAVE',
    BALScroll = 'BAL',
    CAKEScroll = 'CAKE',
    CRVScroll = 'CRV',
    DAIScroll = 'DAI',
    GHOScroll = 'GHO',
    KNCScroll = 'KNC',
    LUSDScroll = 'LUSD',
    RETHScroll = 'rETH',
    UNIScroll = 'UNI',
    USDCScroll = 'USDC',
    USDTScroll = 'USDT',
    WBTCScroll = 'WBTC',
    ETHScroll = 'ETH',
    WETHScroll = 'WETH',
    WSTETHScroll = 'wstETH',
    //PEDScroll = 'PED',
    LABScroll = 'LAB.s',
    AXLUSDC = 'axlUSDC',
    SKYScroll = 'SKY',
    SCROLLYScroll = 'SCROLLY',
    CATScroll = 'CAT',
    EGGROLLScroll = 'EGGROLL',
    PANDAScroll = 'PANDA',
    WASSIEScroll = 'WASSIE',
}

