export enum TokenSymbol {
    ETHManta = 'ETH',
    WETHManta = 'WETH',
    USDTManta = 'USDT',
    USDCManta = 'USDC',
    MANTAManta = 'MANTA',
    DAIManta = 'DAI',
    WBTCManta = 'WBTC',
    WSTETHManta = 'wstETH',
    RETHManta = 'rETH',
    TIAManta = 'TIA',
    ASMManta = 'ASM',
    STONEManta = 'STONE',
    WUSDMManta = 'wUSDM',
    MNUManta = 'MNU',
    MANTEManta = 'MANTE',
    KUMAManta = 'KUMA',
    BELManta = 'BEL',
    MZARDManta = 'MZARD',
    LABManta = 'LAB.m',
    LUBUManta = 'LUBU',
    KENNYManta = 'KENNY',
}
