export enum TokenSymbol {
    PLUMEPlumeNew = 'PLUME',
    WPLUMEPlumeNew = 'WPLUME',
    PUSDPlumeNew = 'pUSD',
    PETHPlumeNew = 'pETH',
    USDCPlumeNew = 'USDC.e',
    USDTPlumeNew = 'USDT',
    NRWAPlumeNew = 'nRWA',
    NTBILLPlumeNew = 'nTBILL',
    NELIXIRPlumeNew = 'nELIXIR',
    NBASISPlumeNew = 'nBASIS',
    NCREDITPlumeNew = 'nCREDIT',
    NALPHAPlumeNew = 'nALPHA',
    ESBTCPlumeNew = 'esBTC',
}
