export enum TokenSymbol {
    SCRScroll = 'SCR',
    AAVEScroll = 'AAVE',
    BALScroll = 'BAL',
    CAKEScroll = 'CAKE',
    CRVScroll = 'CRV',
    DAIScroll = 'DAI',
    GHOScroll = 'GHO',
    KNCScroll = 'KNC',
    LUSDScroll = 'LUSD',
    RETHScroll = 'rETH',
    UNIScroll = 'UNI',
    USDCScroll = 'USDC',
    USDTScroll = 'USDT',
    WBTCScroll = 'WBTC',
    ETHScroll = 'ETH',
    WETHScroll = 'WETH',
    WSTETHScroll = 'wstETH',
    //PEDScroll = 'PED',
    LABScroll = 'LAB.s',
    AXLUSDC = 'axlUSDC',
    SKYScroll = 'SKY',
    SCROLLYScroll = 'SCROLLY',
    CATScroll = 'CAT',
    EGGROLLScroll = 'EGGROLL',
    PANDAScroll = 'PANDA',
    WASSIEScroll = 'WASSIE',
    VENScroll = 'VEN',
    STONEScroll = 'STONE',
    WEETHScroll = 'weETH',
    PUFETHScroll = 'PufETH',
    SWIFScroll = 'SWIF',
    WRSETHScroll = 'wrsETH',
    KALAScroll = 'KALA',
    BAGGORScroll = 'BAGGOR',
    DAPPScroll = 'DAPP',
}

