export enum TokenSymbol {
    USDCZklink =  'USDC',
    USDTZklink =  'USDT',
    WBTCZklink = 'WBTC',
    DAIZklink = 'DAI',
    USDCLineaZklink = 'USDC.Linea',
    USDTLineaZkLink = 'USDT.Linea',
    USDTEthZklink = 'USDT.Eth',
    USDCEthZklink = 'USDC.Eth',
    USDTZkSynZklink = 'USDT.ZkSync',
    USDCZkSyncZklink = 'USDC.ZkSync',
    USDCArbiZkLink = 'USDC.Arbi',
    USDTArbiZkLink = 'USDT.Arbi',
    USDCMantaZkLink = 'USDC.Manta',
    USDCMantleZkLink = 'USDC.Mantle',
    WBTCEthZkLink = 'WBTC.Eth',
    WBTCArbiZkLink = 'WBTC.Arbi',
    BTCTZkLink = 'BTCT',
    SOLVBTCZkLink = 'SolvBTC.m',
    ZKZkLink = 'ZK',
}
