export enum TokenSymbol {
    BEL = 'BEL',
    MAV = 'MAV',
    ZKUSD = 'ZKUSD',
    SPACE = 'SPACE',
    RETH = 'rETH',
    ZKSP = 'ZKSP',
    DEXTF = 'DEXTF',
    BOLT = 'BOLT',
    CHEEMS = 'Cheems',
    SLUSDT = 'slUSDT',
    SLSTETH = 'stETH',
    SLBTC = 'BTC',
    RF = 'RF',
    ZAT = 'ZAT',
    GEJU = 'GEJU',
    VS = 'VS',
    OT = 'OT',
    ERA = 'ERA',
    BLADE = 'BLADE',
    ZNS = 'ZNS',
    ESZKDX = 'esZKDX',
    BANKERPEPE = 'BankerPepe',
    LSD = 'LSD',
    PEPERA = 'PEPERA',
    GGG = 'GGG',
    KANA = 'KANA',
    ZKS = 'ZKS',
    ZKHYT = 'ZKHYT',
    ZKMIT = 'ZKMIT',
    SPIRAL = 'SPIRAL',
    SLR = 'SLR',
    ONEZ = 'ONEZ',
    PIKO = 'PIKO',
    USDLR = 'USDLR',
    HOLD = 'HOLD',
}

