export enum TokenSymbol {
    ZETAZeta = 'ZETA',
    WZETAZeta = 'WZETA',
    ETHETHZeta = 'ETH.ETH',
    BNBBSCZeta = 'BNB.BSC',
    BTCBTCZeta = 'BTC.BTC',
    USDTBSCZeta = 'USDT.BSC',
    USDTETHZeta = 'USDT.ETH',
    USDCBSCZeta = 'USDC.BSC',
    USDCETHZeta = 'USDC.ETH',
    STZETAZeta = 'stZETA',
    STZETA2Zeta = 'stZETA',
    HUHUZeta = 'HUHU',
    RBZeta = 'RB',
    ZCATZeta = 'ZCat',
    ZBRUSDZeta = 'zbrUSD',
    PUFETHZeta = 'pufETH',
    UNIBTCZeta = 'uniBTC',
}
