export enum TokenSymbol {
    OKBXLayer = 'OKB',
    WOKBXLayer = 'WOKB',
    HULUXLayer = 'HULU',
    DUCKXLayer = 'DUCK',
    TCATXLayer = 'TCAT',
    XCAT1XLayer = 'Xcat',
    XCAT2XLayer = 'XCAT',
    XINUXLayer = 'XINU',
    XPEPELayer = 'XPEPE',
    OKOXXLayer = 'OKOX',
    MUKIXLayer = 'MUKI',
    XDOGXLayer = 'XDOG',
    FBXLayer = 'FB',
}
